name: Sphinx Documentation

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ahmad88me/sphinx-docs-action@e4f0e0743c09920f9b4dbfd739d612faa969cfba
        with:
          python-version: '3.8'
          git-username: 'ahmad88me'
          git-email: 'ahmad88me@gmail.com'
          project-path: 'src'
          files-pattern: 'examples/*example*.py'
          commit-message: 'update docs'
          github-token: ${{ secrets.GITHUB_TOKEN }}

